modLoader="javafml"
loaderVersion="[40,)"
license="LGPL 2.1"
issueTrackerURL="https://github.com/jodlodi/BedDontExplode/issues"
[[mods]]
modId="bedsdontexplode"
version="1.0"
displayName="Beds Don't Explode"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="bedsdontexplode.png"
authors="jodlodi"
description='''Beds will no longer explode.'''

[[dependencies.bedsdontexplode]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedsdontexplode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
