modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="bedsdontexplode"
version="${file.jarVersion}"
displayName="Beds Don't Explode"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="bedsdontexplode.png"
credits=""
authors="jodlodi"
description='''
Beds will no longer explode.
'''

[[dependencies.bedsdontexplode]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedsdontexplode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
